### ISSUE TITLE
Investigate Radiant Earth plugin

### ISSUE THREAD

**Issue by lkwalke4** [stac-utils/qgis-stac-plugin#1]
Investigate previous QGIS STAC plugin from Radiant Earth to see if code contains useful items for this project

**Comment by Fanevanjanahary** [comment]
**Planet Explorer**

1. Filters:

-  AOI
     - Get AOI from Selected Feature
     - Upload vector layer

- Other Filters:
    - Cloud cover
    - Source (ex Sentinel-2 Tile, Landsat 8, etc)
    
![WhatsApp Image 2021-11-22 at 10 32 25](https://user-images.githubusercontent.com/12623986/142821447-6c055c9f-fb61-445b-91e8-4d5bc225b75d.jpeg)

2. Results
   

- Group by band and date
- Add layer to map is in a group in which  there are footprints and rasters


![Capture d’écran 2021-11-22 103350](https://user-images.githubusercontent.com/12623986/142821450-3f995887-a9d0-4806-b88a-1fff2ad2e749.png)

It's possible to view the URL API
