### ISSUE TITLE
Main dialog doesn't fit on screen, and can't be resized

### ISSUE THREAD

**Issue by robintw** [stac-utils/qgis-stac-plugin#118]
I'm finding that on my laptop (which has a relatively small screen), the main dialog window opens in such a way that it doesn't fit on the screen properly. The 'search' button at the bottom is off the bottom of the screen, and therefore can't be clicked. I've tried resizing the dialog, but that doesn't seem to work - presumably because there are too many controls to fit in a smaller dialog.

I've got two ideas for how to deal with this:

1. The various filtering options could start in their 'collapsed' state, so that they don't take up as much space.
2. The whole contents of the dialog could be put in a scrollable view, so that even if it takes up too much space, the user can scroll the dialog and eventually get to the end.

**Comment by Samweli** [comment]
@robintw thanks for opening this, the issues raised here have been recently fixed (see https://github.com/stac-utils/qgis-stac-plugin/pull/183).
