### ISSUE TITLE
Extent box coordinates should always be in WSG84

### ISSUE THREAD

**Issue by Samweli** [stac-utils/qgis-stac-plugin#142]
We need to make sure when a user draws or gets bounds from map the coordinates are reprojected to WSG84 from any active coordinate system in use.

**Comment by mmcfarland** [comment]
I attempted to recreate this issue by loading non WSG84 layers and also setting the workspace to a projected CRS and couldn't get the dialog to use different coordinates. This issue may have previously been resolved, or the scenario for recreating it more difficult to get to than I anticipated (though I have seen it occur in the past). I'm good with closing this.

**Comment by Samweli** [comment]
> I attempted to recreate this issue by loading non WSG84 layers and also setting the workspace to a projected CRS and couldn't get the dialog to use different coordinates. This issue may have previously been resolved, or the scenario for recreating it more difficult to get to than I anticipated (though I have seen it occur in the past). I'm good with closing this.

thanks @mmcfarland
