### ISSUE TITLE
Cloud optimized point cloud (COPC) support

### ISSUE THREAD

**Issue by wonder-sk** [stac-utils/qgis-stac-plugin#166]
QGIS 3.26 will come with COPC support out of the box, so it would be great if the STAC plugin could load COPC datasets as map layers!

There are some datasets available at the Planetary Computer for testing:
https://planetarycomputer.microsoft.com/dataset/3dep-lidar-copc

**Comment by Samweli** [comment]
Closed via https://github.com/stac-utils/qgis-stac-plugin/pull/167
