### ISSUE TITLE
"Sort by" should have an option for "none" instead of only for Name and Collection

### ISSUE THREAD

**Issue by philvarner** [stac-utils/qgis-stac-plugin#194]
By default, no sort is sent in the requests. However:

1. The "Sort by" field displays the "Name" option from the dropdown, even though this is not sent.
2. If a user clicks on this dropdown, Name is then selected and used for the sort, which changes the display.

Also, this  seems to only affect the ordering on the page, rather than the query that is sent? I would expect this to do the sort in the query instead of only with the 5 results.

Also adding a "datetime" sortby would be nice.

**Comment by Samweli** [comment]
Hi @philvarner, thanks for opening this issue. We have already fix the first and second concerns you have raised in this issue, see https://github.com/stac-utils/qgis-stac-plugin/pull/141.

The current main branch contains sort by and order by buttons in the search tab, the sort is now sent in the requests and the sort box does have a blank option which when selected sort functionality is not used in the request.

You can test this functionality by downloading the plugin beta version by adding the plugin custom repository in QGIS ( https://stac-utils.github.io/qgis-stac-plugin/repository/plugins.xml)

And yes support for "datetime" sorting will be a good addition.

**Comment by Samweli** [comment]
Opened a new issue https://github.com/stac-utils/qgis-stac-plugin/issues/202
