### ISSUE TITLE
Plugin does not load assets with `href` starting with s3://

### ISSUE THREAD

**Issue by ahuarte47** [stac-utils/qgis-stac-plugin#215]
Plugin is supposing that `href` is always a https link. It would be great the support when `href` represents an AWS S3 key:

This simple change enables to load it.

![image](https://user-images.githubusercontent.com/5576272/191001340-e22b0e3b-762c-4fbc-84fc-666da8ceb93a.png)

**Comment by luipir** [comment]
Hi @Samweli do you prefer a PR adding this fix and move discussion there o it is ok here?

**Comment by ahuarte47** [comment]
If this helps, I have uploaded a PR: https://github.com/stac-utils/qgis-stac-plugin/pull/216

**Comment by Samweli** [comment]
Hi @ahuarte47 thanks for opening this. I will be good to have a one solution for handling all AWS S3 STAC assets in the plugin or none, otherwise we are going to have a lot of plugin code that is catalog specific.

I just had discussion today with providers of https://explorer.digitalearth.africa/stac who have had similar issues accessing their STAC assets using the plugin because of using AWS `href`.I think the `href` should be in a widely used standard, for this case https.

**Comment by ahuarte47** [comment]
Hi @Samweli , thank you very much for your awnser. So, nothing has to be changed.

**Comment by drnextgis** [comment]
If we limit possible values of `href` just to `http(s)` then the plugin won't be able to handle assets located in requester pays [buckets](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#requester-pays) which I would say are widely used. I don't think that adding support of GDAL Virtual File Systems (at least `/vsis3` and `/vsiaz`) will turn into "a lot of plugin code" as you can see from the PR proposed by @ahuarte47.

**Comment by Samweli** [comment]
> Hi @Samweli do you prefer a PR adding this fix and move discussion there o it is ok here?

@luipir I'm -1 on having this change on the plugin code.

**Comment by Samweli** [comment]
> So, nothing has to be changed.

yes @ahuarte47

**Comment by Samweli** [comment]
> If we limit possible values of `href` just to `http(s)` then the plugin won't be able to handle assets located in requester pays [buckets](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#requester-pays) which I would say are widely used.

@drnextgis if we come to conclusion that we will need the support for this in the plugin then using dedicated libraries (eg. [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) ) will be best way.

> I don't think that adding support of GDAL Virtual File Systems (at least `/vsis3` and `/vsiaz`) will turn into "a lot of plugin code" as you can see from the [PR](https://github.com/stac-utils/qgis-stac-plugin/pull/216) proposed by @ahuarte47.

Here I meant that not that the [PR](https://github.com/stac-utils/qgis-stac-plugin/pull/216) contains "a lot of plugin code" but it ll set a precedent on having provider specific functionality on the plugin.

**Comment by Samweli** [comment]
> @Samweli could you please elaborate on why do you think dedicated libraries might be needed if the GDAL (which is already a dependency for the plugin) can manage those `/vsi*` URLs by itself?

@drnextgis adding the item assets as layers is one of the plugin functionalities, the plugin also support downloading item assets and it also access/fetch some of the assets, the solution offered here only target loading the asset into QGIS as a layer, we need a solution that will cover all the plugin parts that deals with the item asset resources.

**Comment by drnextgis** [comment]
I see your point @Samweli but we still can avoid introducing new dependencies and generate HTTP URLs out of `/vsi*` with GDAL that can be used for downloading assets:
```python
>>> from osgeo import gdal
>>> gdal.GetSignedURL("/vsis3/my-dummy-bucket/test.tif")
>>> ''https://my-dummy-bucket/...'
```

**Comment by ahuarte47** [comment]
Hi @Samweli I have changed the PR to add more generality. Even we are managing HTTP[s] URLs as you recommend. Thanks @drnextgis, you guided to me for this elegant solution. What do you think?

**Comment by Samweli** [comment]
> I see your point @Samweli but we still can avoid introducing new dependencies and generate HTTP URLs out of `/vsis3` with GDAL which can be used for downloading assets:

@drnextgis I see, I think we should open a new issue that will align with your suggested solution and the PR https://github.com/stac-utils/qgis-stac-plugin/pull/216  because they only work for the GDAL related assets instead of all assets as indicated on this issue.

**Comment by ahuarte47** [comment]
Ok @Samweli I close this issue and related [PR](https://github.com/stac-utils/qgis-stac-plugin/pull/216). I am going to create new ones for GDAL related assets.
