### ISSUE TITLE
Create test infrastructure

### ISSUE THREAD

**Issue by lkwalke4** [stac-utils/qgis-stac-plugin#6]
Setup infrastructure for testing in the plugin, the test suite should cover plugin functional features and include a mockup stac-api server for testing plugin functionality against stac-api spec.
The setup should enable running tests against QGIS LTR, QGIS nightly and QGIS 3.22 versions. See https://github.com/qgis/QGIS/tree/master/.docker/qgis_resources/test_runner for reference in running plugin test inside QGIS application.

**Comment by Samweli** [comment]
Fixed in https://github.com/stac-utils/qgis-stac-plugin/pull/17
