### ISSUE TITLE
Use Item GeoJSON when adding item footprint

### ISSUE THREAD

**Issue by mmcfarland** [stac-utils/qgis-stac-plugin#74]
When adding the item footprint, it appears that the geometry is added as a new layer. The item object itself is a valid GeoJSON object, and has valuable metadata in its `properties` field. Is it possible to just use the Item GeoJSON directly, and not create a new geometry so that the user can access the properties through QGIS? 

I'm assuming this isn't the case currently, because there were not properties on the added footprints:

![image](https://user-images.githubusercontent.com/1014341/146952763-c371f2f5-9b06-4e8b-a65a-9203579f4e95.png)

**Comment by Samweli** [comment]
@mmcfarland right, do you know which properties will be nice to have for the footprint, or we should load all the available properties?

**Comment by mmcfarland** [comment]
@Samweli The contents of `properties` will be variable depending on the collection, so I'd suggest just using the full properties object.
